// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	Suit  string `json:"suit"`
	Rank  string `json:"rank"`
	Value int    `json:"value"`
}

type Game struct {
	ID          *string `json:"id,omitempty"`
	PlayerHand  []*Card `json:"playerHand"`
	DealerHand  []*Card `json:"dealerHand"`
	Status      string  `json:"status"`
	PlayerScore *int    `json:"playerScore,omitempty"`
	DealerScore *int    `json:"dealerScore,omitempty"`
	Deck        []*Card `json:"deck"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
